name: vendredi
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.1.6  # Corrigé ici (google au lieu de oogle)
  flutter_contacts: ^1.1.7+1
  intl: ^0.18.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

flutter:
  assets:
    - assets/qr_code.png
    - assets/google_logo.png

uses-material-design: true
