// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmX_BV3X-3jHdWJ9SFhCwWfdKrQ6fuIuo',
    appId: '1:540700617185:web:d9e8e52868f661988f0aa0',
    messagingSenderId: '540700617185',
    projectId: 'vendredi-22b76',
    authDomain: 'vendredi-22b76.firebaseapp.com',
    storageBucket: 'vendredi-22b76.firebasestorage.app',
    measurementId: 'G-J736L1BL9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6zXq4fTImRG9EgmInv4C0579JPlhcJDg',
    appId: '1:540700617185:android:31d24da56df924168f0aa0',
    messagingSenderId: '540700617185',
    projectId: 'vendredi-22b76',
    storageBucket: 'vendredi-22b76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsbLsFrgy_yWxFoj0aPrPVZVwLcLqLCFo',
    appId: '1:540700617185:ios:855a5dadb29347c88f0aa0',
    messagingSenderId: '540700617185',
    projectId: 'vendredi-22b76',
    storageBucket: 'vendredi-22b76.firebasestorage.app',
    iosBundleId: 'com.vendredi.vendredi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsbLsFrgy_yWxFoj0aPrPVZVwLcLqLCFo',
    appId: '1:540700617185:ios:855a5dadb29347c88f0aa0',
    messagingSenderId: '540700617185',
    projectId: 'vendredi-22b76',
    storageBucket: 'vendredi-22b76.firebasestorage.app',
    iosBundleId: 'com.vendredi.vendredi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmX_BV3X-3jHdWJ9SFhCwWfdKrQ6fuIuo',
    appId: '1:540700617185:web:b338644614926ff08f0aa0',
    messagingSenderId: '540700617185',
    projectId: 'vendredi-22b76',
    authDomain: 'vendredi-22b76.firebaseapp.com',
    storageBucket: 'vendredi-22b76.firebasestorage.app',
    measurementId: 'G-J2ME8N6B2S',
  );

}